---
- name: Install basic stuff
  ansible.builtin.package:
    name:
      - vim
      - curl
      - wget
      - git
      - autoconf
      - build-essential
      - libncurses-dev
      - libssl-dev
    state: present
