---
- name: Install Bluetooth packages
  ansible.builtin.apt:
    name:
      - bluetooth
      - bluez
      - bluez-tools
      - blueman
      - libspa-0.2-bluetooth
    state: present

- name: Ensure Bluetooth service is running and enabled
  ansible.builtin.service:
    name: bluetooth
    state: started
    enabled: yes
