- name: Install xssproxy
  ansible.builtin.package:
    update_cache: yes
    name: xssproxy

- name: Find xssproxy binary
  ansible.builtin.set_fact:
    xssproxy_bin: "{{ lookup('pipe', 'which xssproxy') }}"

- name: Systemd Unit
  ansible.builtin.template:
    src: "xssproxy.service.j2"
    dest: "/usr/lib/systemd/user/xssproxy.service"
    owner: "{{ user }}"
    group: "{{ user }}"

# - name: Enable xssproxy service
#   ansible.builtin.systemd_service:
#     name: xssproxy
#     state: started
#     enabled: yes
#     scope: "user"
