---
- name: Install i3 and LightDM
  ansible.builtin.package:
    name:
      - i3
      - lightdm
      - guake
      - rofi
      - thunar
      - gvfs
      - gvfs-backends
      - gnome-keyring
      - network-manager-gnome
      # screenshots
      - maim
      - scrot
      - xclip
    state: present

- name: Enable LightDM service
  ansible.builtin.service:
    name: lightdm
    enabled: yes

- name: Create i3 config directory
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/i3"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'

- name: Template i3 config
  ansible.builtin.template:
    src: i3.config.j2
    dest: "{{ home_dir }}/.config/i3/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
