---
- name: Ensure sudo is installed
  ansible.builtin.package:
    name: sudo
    state: present
    update_cache: yes

- name: Disable root password
  ansible.builtin.user:
    name: root
    password: '!'
    update_password: always

- name: Ensure user is in sudo group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: sudo
    append: yes
