---
- name: Import a gpg key from a url
  ansible.builtin.get_url:
    url: "https://download.sublimetext.com/sublimehq-pub.gpg"
    dest: "/etc/apt/keyrings/sublimehq-pub.asc"

# Types: deb
# URIs: https://download.sublimetext.com/
# Suites: apt/stable/
# Signed-By: /etc/apt/keyrings/sublimehq-pub.asc
- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/sublimehq-pub.asc] https://download.sublimetext.com/ apt/stable/"
    filename: sublime-text
    state: present

- name: Install Sublime
  ansible.builtin.package:
    name: sublime-text
    state: present
    update_cache: yes
